services:
   redis:
        image: "redis:alpine"
        container_name: "my_redis"
        ports:
        - "6379:6379"
        volumes:        ## Persist Redis data to save it across container restarts or crashes (the electricity may go out :))).
        - redis_data:/data
        restart: unless-stopped
volumes:
  redis_data: